import Foundation
import SwiftUI
import UniformTypeIdentifiers

enum AppLanguage: String, CaseIterable, Identifiable {
    case system, en, de, fr, es, it, pt, nl, pl, ja, zh
    var id: String { rawValue }

    var displayName: String {
        switch self {
        case .system: return L10n.t("language.system")
        case .en: return "English"
        case .de: return "Deutsch"
        case .fr: return "Français"
        case .es: return "Español"
        case .it: return "Italiano"
        case .pt: return "Português"
        case .nl: return "Nederlands"
        case .pl: return "Polski"
        case .ja: return "日本語"
        case .zh: return "简体中文"
        }
    }

    static var resolvedCode: String {
        let stored = UserDefaults.standard.string(forKey: "unarchive.language") ?? AppLanguage.system.rawValue
        if stored != AppLanguage.system.rawValue { return stored }
        let preferred = Locale.preferredLanguages.first ?? "en"
        let prefix = String(preferred.prefix(2)).lowercased()
        let supported = ["en", "de", "fr", "es", "it", "pt", "nl", "pl", "ja", "zh"]
        return supported.contains(prefix) ? prefix : "en"
    }
}

enum AppAppearance: String, CaseIterable, Identifiable {
    case system, light, dark
    var id: String { rawValue }

    var colorScheme: ColorScheme? {
        switch self {
        case .system: return nil
        case .light: return .light
        case .dark: return .dark
        }
    }

    var title: String {
        switch self {
        case .system: return L10n.t("appearance.system")
        case .light: return L10n.t("appearance.light")
        case .dark: return L10n.t("appearance.dark")
        }
    }
}

enum CreateFormat: String, CaseIterable, Identifiable {
    case zip, sevenZip, tar, tarGz, tarBz2, tarXz
    var id: String { rawValue }

    var fileExtension: String {
        switch self {
        case .zip: return "zip"
        case .sevenZip: return "7z"
        case .tar: return "tar"
        case .tarGz: return "tar.gz"
        case .tarBz2: return "tar.bz2"
        case .tarXz: return "tar.xz"
        }
    }

    var title: String {
        switch self {
        case .zip: return "ZIP"
        case .sevenZip: return "7z"
        case .tar: return "TAR"
        case .tarGz: return "TAR.GZ"
        case .tarBz2: return "TAR.BZ2"
        case .tarXz: return "TAR.XZ"
        }
    }

    var contentType: UTType {
        switch self {
        case .zip: return .zip
        case .sevenZip: return UTType(filenameExtension: "7z") ?? .data
        case .tar: return UTType(filenameExtension: "tar") ?? .data
        case .tarGz: return UTType(filenameExtension: "gz") ?? .data
        case .tarBz2: return UTType(filenameExtension: "bz2") ?? .data
        case .tarXz: return UTType(filenameExtension: "xz") ?? .data
        }
    }
}

enum L10n {
    static func t(_ key: String, _ args: CVarArg...) -> String {
        let code = AppLanguage.resolvedCode
        let template = tables[code]?[key] ?? tables["en"]?[key] ?? key
        guard !args.isEmpty else { return template }
        return String(format: template, arguments: args)
    }

    private static let tables: [String: [String: String]] = [
        "en": en, "de": de, "fr": fr, "es": es, "it": it,
        "pt": pt, "nl": nl, "pl": pl, "ja": ja, "zh": zh
    ]

    private static let en: [String: String] = [
        "app.name": "Unarchive",
        "created.by": "Created by Shambhala222",
        "open": "Open",
        "open.archive": "Open Archive…",
        "extract.to": "Extract To…",
        "extract.here": "Unpack at Archive",
        "extract.folder": "Unpack to Subfolder",
        "extract.to.help": "Choose a folder and unpack there.",
        "extract.here.help": "Unpack into the same folder as the .rar file.",
        "extract.folder.help": "Create a folder next to the archive and unpack into it.",
        "test": "Test",
        "search": "Search",
        "create": "Create",
        "create.archive": "Create Archive…",
        "settings": "Settings",
        "about": "About",
        "welcome.title": "Unpack any archive",
        "welcome.subtitle": "Drop a RAR, ZIP, 7z or TAR file here. Drag files out, extract with a click, or pack a new archive.",
        "drop.title": "Drop archive here",
        "drop.subtitle": "or choose a file to browse its contents",
        "formats.unpack": "Unpack",
        "formats.pack": "Create",
        "recent": "Recent",
        "password": "Password",
        "password.enter": "Enter password",
        "password.protected": "“%@” is password protected.",
        "password.wrong": "That password is incorrect. Try again.",
        "password.needed.extract": "A password is required to extract.",
        "password.needed.open": "A password is required to open this file.",
        "password.needed.test": "A password is required to test the archive.",
        "password.trying": "Trying saved passwords…",
        "password.remember": "Remember working passwords",
        "password.remember.help": "Unarchive keeps them in its own password archive (not your Safari or Wi-Fi keychain). When a new archive is protected, it tries those first.",
        "password.saved": "Passwords in Unarchive",
        "password.saved.count": "Working passwords (%d)",
        "password.clear": "Delete all",
        "password.archive": "Archive passwords",
        "password.add": "Add",
        "password.delete": "Delete",
        "password.show": "Show",
        "password.hide": "Hide",
        "password.teach": "Add a known password",
        "password.teach.help": "Only passwords that actually open archives belong here. Unarchive tries them automatically on the next protected file.",
        "password.empty": "Nothing saved yet. Successful passwords appear here, or add one yourself.",
        "cancel": "Cancel",
        "unpack": "Unpack",
        "wait": "Please wait…",
        "notice": "Notice",
        "error": "Error",
        "ok": "OK",
        "status.idle": "Open an archive or drop a file onto this window.",
        "status.selected": "%d selected · %d files · %@",
        "status.selected.volumes": "%d selected · %d files · %@ content · %d parts · archive %@",
        "status.listing": "%d files · %@ · %@",
        "status.listing.sizes": "%d files · %@ content · %@ archive",
        "status.listing.volumes": "%d parts · %d files · %@ content · %@ archive",
        "status.volumes": "%d parts",
        "status.volumes.help": "All split volumes of this archive, counted from the files next to the one you opened.",
        "status.format.help": "%@ is the archive format.",
        "selection": "Selection",
        "show.finder": "Show in Finder",
        "copy.names": "Copy Names",
        "info": "Get Info",
        "set.default": "Use Unarchive for Archives",
        "language": "Language",
        "language.system": "System",
        "appearance": "Appearance",
        "appearance.system": "System",
        "appearance.light": "Light",
        "appearance.dark": "Dark",
        "general": "General",
        "extraction": "Extraction",
        "creating": "Create",
        "reveal.after": "Show destination in Finder after extracting",
        "default.format": "Default format for new archives",
        "about.body": "Unarchive is a native macOS tool for browsing, extracting and creating archives. Built for Apple Silicon.",
        "version": "Version %@ (%@)",
        "copyright": "Copyright © 2026 Shambhala222. All rights reserved.",
        "path": "Path",
        "type": "Kind",
        "folder": "Folder",
        "file": "File",
        "files": "files",
        "method": "Compression",
        "modified": "Modified",
        "encrypted": "Encrypted",
        "yes": "Yes",
        "not.supported": "“%@” is not a supported archive.",
        "create.choose": "Choose files or folders to pack",
        "create.save": "Save Archive",
        "create.failed": "The archive could not be created.",
        "create.done": "Archive created.",
        "column.name": "Name",
        "column.size": "Size",
        "column.packed": "Packed",
        "column.date": "Modified",
        "reading": "Reading archive…",
        "extracting": "Extracting…",
        "preparing": "Preparing file…",
        "testing": "Testing archive…",
        "extracted.to": "Finished extracting to “%@”.",
        "extracted.to.time": "Finished extracting to “%@” in %@.",
        "extract.cancel": "Stop unpacking",
        "extract.cancelled": "Unpacking was stopped.",
        "extract.busy": "Unpacking is already in progress.",
        "progress.file": "File",
        "progress.to": "Destination",
        "progress.part": "Volume",
        "progress.files": "file %d of %d",
        "progress.elapsed": "Elapsed %@",
        "progress.eta": "About %@ left",
        "progress.eta.wait": "Calculating remaining time…",
        "progress.finishing": "Finishing…",
        "progress.volume": "Reading %@",
        "test.ok": "The archive tested successfully. All files are intact.",
        "test.fail": "The test finished with errors.\n\n%@",
        "default.ok": "Unarchive now opens archives on double-click, including RAR, ZIP, 7z and similar formats.",
        "default.fail": "macOS did not change the default. Right-click a RAR file → Open With → Unarchive → Always.",
        "close.archive": "Close",
        "choose.folder": "Choose Destination",
        "pack.note": "Create ZIP, 7z, TAR, TAR.GZ, TAR.BZ2 or TAR.XZ. RAR packing is not included because that format is proprietary.",
        "feature.multiselect": "Multi-select and drag files into Finder",
        "feature.password": "Password prompt for protected archives",
        "feature.context": "Right-click to extract, preview or inspect",
        "helper.missing": "The unpacking engine could not be found.",
        "list.failed": "The archive could not be read.",
        "extract.failed": "Extraction failed.",
        "not.an.archive": "This file is not a supported archive.",
        "invalid.listing": "Invalid archive response.",
        "no.recent": "No recent archives yet.",
        "open.selection": "Open",
        "credits": "Created and designed by Shambhala222",
        "engine": "Extraction engine: UnRAR for RAR · 7-Zip for 7z · The Unarchiver for ZIP and others",
        "legal": "This product is not affiliated with WinRAR or RARLAB."
    ]

    private static let de: [String: String] = [
        "created.by": "Erstellt von Shambhala222",
        "open": "Öffnen",
        "open.archive": "Archiv öffnen…",
        "extract.to": "Entpacken nach…",
        "extract.here": "Am Archivort entpacken",
        "extract.folder": "In Unterordner entpacken",
        "extract.to.help": "Ordner wählen und dorthin entpacken.",
        "extract.here.help": "Entpackt in denselben Ordner, in dem die Archivdatei liegt.",
        "extract.folder.help": "Legt neben dem Archiv einen Ordner an und entpackt dorthin.",
        "test": "Prüfen",
        "search": "Suchen",
        "create": "Erstellen",
        "create.archive": "Archiv erstellen…",
        "settings": "Einstellungen",
        "about": "Über",
        "welcome.title": "Jedes Archiv öffnen",
        "welcome.subtitle": "Ziehe eine RAR-, ZIP-, 7z- oder TAR-Datei hierher. Dateien rausziehen, per Klick entpacken oder ein neues Archiv packen.",
        "drop.title": "Archiv hierher ziehen",
        "drop.subtitle": "oder eine Datei wählen, um den Inhalt zu sehen",
        "formats.unpack": "Entpacken",
        "formats.pack": "Erstellen",
        "recent": "Zuletzt geöffnet",
        "password": "Passwort",
        "password.enter": "Passwort eingeben",
        "password.protected": "„%@“ ist passwortgeschützt.",
        "password.wrong": "Das Passwort ist falsch. Bitte erneut versuchen.",
        "password.needed.extract": "Zum Entpacken wird ein Passwort benötigt.",
        "password.needed.open": "Zum Öffnen wird ein Passwort benötigt.",
        "password.needed.test": "Zum Prüfen wird ein Passwort benötigt.",
        "password.trying": "Gespeicherte Passwörter werden geprüft…",
        "password.remember": "Funktionierende Passwörter merken",
        "password.remember.help": "Unarchive legt sie in einem eigenen Passwortarchiv ab – nicht in deinem Safari- oder WLAN-Schlüsselbund. Bei einem neuen Archiv werden sie zuerst ausprobiert.",
        "password.saved": "Passwörter in Unarchive",
        "password.saved.count": "Funktionierende Passwörter (%d)",
        "password.clear": "Alle löschen",
        "password.archive": "Archiv-Passwörter",
        "password.add": "Hinzufügen",
        "password.delete": "Löschen",
        "password.show": "Anzeigen",
        "password.hide": "Verbergen",
        "password.teach": "Bekanntes Passwort eintragen",
        "password.teach.help": "Nur Passwörter, die Archive wirklich öffnen. Unarchive probiert sie beim nächsten geschützten Archiv automatisch durch.",
        "password.empty": "Noch nichts gespeichert. Erfolgreiche Passwörter erscheinen hier, oder du trägst eines selbst ein.",
        "cancel": "Abbrechen",
        "unpack": "Entpacken",
        "wait": "Bitte warten…",
        "notice": "Hinweis",
        "error": "Fehler",
        "ok": "OK",
        "status.idle": "Archiv öffnen oder eine Datei auf das Fenster ziehen.",
        "status.selected": "%d ausgewählt · %d Dateien · %@",
        "status.selected.volumes": "%d ausgewählt · %d Dateien · Inhalt %@ · %d Teile · Archiv %@",
        "status.listing": "%d Dateien · %@ · %@",
        "status.listing.sizes": "%d Dateien · Inhalt %@ · Archiv %@",
        "status.listing.volumes": "%d Teile · %d Dateien · Inhalt %@ · Archiv %@",
        "status.volumes": "%d Teile",
        "status.volumes.help": "Alle Teildateien dieses Archivs, gezählt im selben Ordner wie die geöffnete Datei.",
        "status.format.help": "%@ ist das Archivformat.",
        "selection": "Auswahl",
        "show.finder": "Im Finder zeigen",
        "copy.names": "Namen kopieren",
        "info": "Informationen",
        "set.default": "Unarchive für Archive verwenden",
        "language": "Sprache",
        "language.system": "System",
        "appearance": "Erscheinungsbild",
        "appearance.system": "System",
        "appearance.light": "Hell",
        "appearance.dark": "Dunkel",
        "general": "Allgemein",
        "extraction": "Entpacken",
        "creating": "Erstellen",
        "reveal.after": "Zielordner nach dem Entpacken im Finder zeigen",
        "default.format": "Standardformat für neue Archive",
        "about.body": "Unarchive ist ein natives macOS-Werkzeug zum Durchsuchen, Entpacken und Erstellen von Archiven. Für Apple Silicon.",
        "version": "Version %@ (%@)",
        "copyright": "Copyright © 2026 Shambhala222. Alle Rechte vorbehalten.",
        "path": "Pfad",
        "type": "Typ",
        "folder": "Ordner",
        "file": "Datei",
        "files": "Dateien",
        "method": "Verfahren",
        "modified": "Geändert",
        "encrypted": "Verschlüsselt",
        "yes": "Ja",
        "not.supported": "„%@“ ist kein unterstütztes Archiv.",
        "create.choose": "Dateien oder Ordner zum Packen wählen",
        "create.save": "Archiv speichern",
        "create.failed": "Das Archiv konnte nicht erstellt werden.",
        "create.done": "Archiv erstellt.",
        "column.name": "Name",
        "column.size": "Größe",
        "column.packed": "Gepackt",
        "column.date": "Geändert",
        "reading": "Archiv wird gelesen…",
        "extracting": "Entpacken…",
        "preparing": "Datei wird vorbereitet…",
        "testing": "Archiv wird geprüft…",
        "extracted.to": "Fertig entpackt nach „%@“.",
        "extracted.to.time": "Fertig entpackt nach „%@“ in %@.",
        "extract.cancel": "Entpacken abbrechen",
        "extract.cancelled": "Entpacken wurde abgebrochen.",
        "extract.busy": "Es wird bereits entpackt.",
        "progress.file": "Datei",
        "progress.to": "Ziel",
        "progress.part": "Teil",
        "progress.files": "Datei %d von %d",
        "progress.elapsed": "Dauer %@",
        "progress.eta": "Noch ca. %@",
        "progress.eta.wait": "Restzeit wird ermittelt…",
        "progress.finishing": "Abschluss…",
        "progress.volume": "Lese %@",
        "test.ok": "Prüfung erfolgreich. Das Archiv ist in Ordnung.",
        "test.fail": "Prüfung abgeschlossen – es gab Fehler.\n\n%@",
        "default.ok": "Unarchive öffnet jetzt Archive per Doppelklick, inklusive RAR, ZIP, 7z und ähnlicher Formate.",
        "default.fail": "macOS hat die Zuordnung nicht übernommen. Rechtsklick auf eine RAR-Datei → Öffnen mit → Unarchive → Immer.",
        "close.archive": "Schließen",
        "choose.folder": "Zielordner wählen",
        "pack.note": "Erstelle ZIP, 7z, TAR, TAR.GZ, TAR.BZ2 oder TAR.XZ. RAR-Packen ist nicht enthalten, weil das Format proprietär ist.",
        "feature.multiselect": "Mehrfachauswahl und Drag & Drop in den Finder",
        "feature.password": "Passwortabfrage für geschützte Archive",
        "feature.context": "Rechtsklick zum Entpacken, Anzeigen oder Prüfen",
        "helper.missing": "Die Entpack-Hilfe konnte nicht gefunden werden.",
        "list.failed": "Das Archiv konnte nicht gelesen werden.",
        "extract.failed": "Entpacken ist fehlgeschlagen.",
        "not.an.archive": "Diese Datei ist kein unterstütztes Archiv.",
        "invalid.listing": "Ungültige Archiv-Antwort.",
        "no.recent": "Noch keine zuletzt geöffneten Archive.",
        "open.selection": "Öffnen",
        "credits": "Erstellt und gestaltet von Shambhala222",
        "engine": "Entpack-Engine: UnRAR für RAR · 7-Zip für 7z · The Unarchiver für ZIP und andere",
        "legal": "Dieses Produkt ist nicht mit WinRAR oder RARLAB verbunden."
    ]

    private static let fr: [String: String] = [
        "created.by": "Créé par Shambhala222",
        "open": "Ouvrir", "open.archive": "Ouvrir l’archive…", "extract.to": "Extraire vers…",
        "extract.here": "Extraire à l’archive", "extract.folder": "Extraire dans un dossier", "test": "Tester",
        "search": "Rechercher", "create": "Créer", "create.archive": "Créer une archive…",
        "settings": "Réglages", "about": "À propos",
        "welcome.title": "Ouvrez n’importe quelle archive",
        "welcome.subtitle": "Déposez un fichier RAR, ZIP, 7z ou TAR. Glissez les fichiers, extrayez en un clic, ou créez une nouvelle archive.",
        "drop.title": "Déposer l’archive ici", "drop.subtitle": "ou choisir un fichier pour en voir le contenu",
        "formats.unpack": "Extraire", "formats.pack": "Créer", "recent": "Récents",
        "password": "Mot de passe", "password.enter": "Saisir le mot de passe",
        "password.protected": "« %@ » est protégé par mot de passe.",
        "password.wrong": "Mot de passe incorrect. Réessayez.",
        "password.needed.extract": "Un mot de passe est requis pour extraire.",
        "password.needed.open": "Un mot de passe est requis pour ouvrir.",
        "password.needed.test": "Un mot de passe est requis pour tester.",
        "cancel": "Annuler", "unpack": "Extraire", "wait": "Veuillez patienter…",
        "notice": "Information", "error": "Erreur", "ok": "OK",
        "status.idle": "Ouvrez une archive ou déposez un fichier sur cette fenêtre.",
        "status.selected": "%d sélectionné(s) · %d fichiers · %@",
        "status.listing": "%d fichiers · %@ · %@",
        "selection": "Sélection", "show.finder": "Afficher dans le Finder", "copy.names": "Copier les noms",
        "info": "Lire les informations", "set.default": "Utiliser Unarchive pour les archives",
        "language": "Langue", "language.system": "Système", "appearance": "Apparence",
        "appearance.system": "Système", "appearance.light": "Clair", "appearance.dark": "Sombre",
        "general": "Général", "extraction": "Extraction", "creating": "Création",
        "reveal.after": "Afficher la destination dans le Finder après extraction",
        "default.format": "Format par défaut des nouvelles archives",
        "about.body": "Unarchive est un outil natif macOS pour parcourir, extraire et créer des archives. Conçu pour Apple Silicon.",
        "version": "Version %@ (%@)", "copyright": "Copyright © 2026 Shambhala222. Tous droits réservés.",
        "path": "Chemin", "type": "Type", "folder": "Dossier", "file": "Fichier", "files": "fichiers",
        "method": "Compression", "modified": "Modifié", "encrypted": "Chiffré", "yes": "Oui",
        "not.supported": "« %@ » n’est pas une archive prise en charge.",
        "create.choose": "Choisir des fichiers ou dossiers à compresser",
        "create.save": "Enregistrer l’archive", "create.failed": "Impossible de créer l’archive.",
        "create.done": "Archive créée.", "column.name": "Nom", "column.size": "Taille",
        "column.packed": "Compressé", "column.date": "Modifié",
        "reading": "Lecture de l’archive…", "extracting": "Extraction…", "preparing": "Préparation…",
        "testing": "Test de l’archive…", "extracted.to": "Extraction terminée vers « %@ ».",
        "test.ok": "Test réussi. L’archive est intacte.", "test.fail": "Le test s’est terminé avec des erreurs.\n\n%@",
        "default.ok": "Unarchive ouvre désormais les archives par double-clic.",
        "default.fail": "macOS n’a pas changé l’app par défaut. Clic droit → Ouvrir avec → Unarchive → Toujours.",
        "close.archive": "Fermer", "choose.folder": "Choisir la destination",
        "pack.note": "Créez ZIP, 7z, TAR, TAR.GZ, TAR.BZ2 ou TAR.XZ. La création RAR n’est pas incluse (format propriétaire).",
        "feature.multiselect": "Sélection multiple et glisser-déposer vers le Finder",
        "feature.password": "Demande de mot de passe pour les archives protégées",
        "feature.context": "Clic droit pour extraire, prévisualiser ou inspecter",
        "helper.missing": "Le moteur d’extraction est introuvable.",
        "list.failed": "Impossible de lire l’archive.", "extract.failed": "Échec de l’extraction.",
        "not.an.archive": "Ce fichier n’est pas une archive prise en charge.",
        "invalid.listing": "Réponse d’archive invalide.", "no.recent": "Aucune archive récente.",
        "open.selection": "Ouvrir", "credits": "Créé et conçu par Shambhala222",
        "engine": "Moteur : UnRAR pour RAR · The Unarchiver pour ZIP et autres · 7-Zip pour la création 7z",
        "legal": "Ce produit n’est pas affilié à WinRAR ou RARLAB."
    ]

    private static let es: [String: String] = [
        "created.by": "Creado por Shambhala222",
        "open": "Abrir", "open.archive": "Abrir archivo…", "extract.to": "Extraer en…",
        "extract.here": "Extraer junto al archivo", "extract.folder": "Extraer a carpeta", "test": "Comprobar",
        "search": "Buscar", "create": "Crear", "create.archive": "Crear archivo…",
        "settings": "Ajustes", "about": "Acerca de",
        "welcome.title": "Abre cualquier archivo comprimido",
        "welcome.subtitle": "Suelta un RAR, ZIP, 7z o TAR. Arrastra archivos, extrae con un clic o crea uno nuevo.",
        "drop.title": "Suelta el archivo aquí", "drop.subtitle": "o elige un archivo para ver su contenido",
        "formats.unpack": "Extraer", "formats.pack": "Crear", "recent": "Recientes",
        "password": "Contraseña", "password.enter": "Introduce la contraseña",
        "password.protected": "“%@” está protegido con contraseña.",
        "password.wrong": "Contraseña incorrecta. Inténtalo de nuevo.",
        "password.needed.extract": "Se necesita una contraseña para extraer.",
        "password.needed.open": "Se necesita una contraseña para abrir.",
        "password.needed.test": "Se necesita una contraseña para comprobar.",
        "cancel": "Cancelar", "unpack": "Extraer", "wait": "Espera…",
        "notice": "Aviso", "error": "Error", "ok": "OK",
        "status.idle": "Abre un archivo o suéltalo en esta ventana.",
        "status.selected": "%d seleccionados · %d archivos · %@",
        "status.listing": "%d archivos · %@ · %@",
        "selection": "Selección", "show.finder": "Mostrar en el Finder", "copy.names": "Copiar nombres",
        "info": "Información", "set.default": "Usar Unarchive para archivos",
        "language": "Idioma", "language.system": "Sistema", "appearance": "Apariencia",
        "appearance.system": "Sistema", "appearance.light": "Claro", "appearance.dark": "Oscuro",
        "general": "General", "extraction": "Extracción", "creating": "Crear",
        "reveal.after": "Mostrar destino en el Finder al extraer",
        "default.format": "Formato predeterminado para archivos nuevos",
        "about.body": "Unarchive es una herramienta nativa de macOS para explorar, extraer y crear archivos. Para Apple Silicon.",
        "version": "Versión %@ (%@)", "copyright": "Copyright © 2026 Shambhala222. Todos los derechos reservados.",
        "path": "Ruta", "type": "Tipo", "folder": "Carpeta", "file": "Archivo", "files": "archivos",
        "method": "Compresión", "modified": "Modificado", "encrypted": "Cifrado", "yes": "Sí",
        "not.supported": "“%@” no es un archivo compatible.",
        "create.choose": "Elige archivos o carpetas para comprimir",
        "create.save": "Guardar archivo", "create.failed": "No se pudo crear el archivo.",
        "create.done": "Archivo creado.", "column.name": "Nombre", "column.size": "Tamaño",
        "column.packed": "Comprimido", "column.date": "Modificado",
        "reading": "Leyendo archivo…", "extracting": "Extrayendo…", "preparing": "Preparando…",
        "testing": "Comprobando archivo…", "extracted.to": "Extracción terminada en “%@”.",
        "test.ok": "Comprobación correcta. El archivo está intacto.",
        "test.fail": "La comprobación terminó con errores.\n\n%@",
        "default.ok": "Unarchive ahora abre archivos con doble clic.",
        "default.fail": "macOS no cambió la app predeterminada. Clic derecho → Abrir con → Unarchive → Siempre.",
        "close.archive": "Cerrar", "choose.folder": "Elegir destino",
        "pack.note": "Crea ZIP, 7z, TAR, TAR.GZ, TAR.BZ2 o TAR.XZ. No se puede crear RAR (formato propietario).",
        "feature.multiselect": "Selección múltiple y arrastrar al Finder",
        "feature.password": "Pide contraseña si el archivo está protegido",
        "feature.context": "Clic derecho para extraer, ver o inspeccionar",
        "helper.missing": "No se encontró el motor de extracción.",
        "list.failed": "No se pudo leer el archivo.", "extract.failed": "La extracción falló.",
        "not.an.archive": "Este archivo no es un archivo compatible.",
        "invalid.listing": "Respuesta de archivo no válida.", "no.recent": "Aún no hay archivos recientes.",
        "open.selection": "Abrir", "credits": "Creado y diseñado por Shambhala222",
        "engine": "Motor: UnRAR para RAR · The Unarchiver para ZIP y otros · 7-Zip para crear 7z",
        "legal": "Este producto no está afiliado con WinRAR ni RARLAB."
    ]

    private static let it: [String: String] = [
        "created.by": "Creato da Shambhala222",
        "open": "Apri", "open.archive": "Apri archivio…", "extract.to": "Estrai in…",
        "extract.here": "Estrai accanto all’archivio", "extract.folder": "Estrai in cartella", "test": "Verifica",
        "search": "Cerca", "create": "Crea", "create.archive": "Crea archivio…",
        "settings": "Impostazioni", "about": "Informazioni",
        "welcome.title": "Apri qualsiasi archivio",
        "welcome.subtitle": "Trascina un file RAR, ZIP, 7z o TAR. Estrai i file o crea un nuovo archivio.",
        "drop.title": "Trascina l’archivio qui", "drop.subtitle": "oppure scegli un file per vederne il contenuto",
        "formats.unpack": "Estrai", "formats.pack": "Crea", "recent": "Recenti",
        "password": "Password", "password.enter": "Inserisci la password",
        "password.protected": "“%@” è protetto da password.",
        "password.wrong": "Password errata. Riprova.",
        "password.needed.extract": "Serve una password per estrarre.",
        "password.needed.open": "Serve una password per aprire.",
        "password.needed.test": "Serve una password per verificare.",
        "cancel": "Annulla", "unpack": "Estrai", "wait": "Attendere…",
        "notice": "Avviso", "error": "Errore", "ok": "OK",
        "status.idle": "Apri un archivio o trascinalo in questa finestra.",
        "status.selected": "%d selezionati · %d file · %@",
        "status.listing": "%d file · %@ · %@",
        "selection": "Selezione", "show.finder": "Mostra nel Finder", "copy.names": "Copia nomi",
        "info": "Informazioni", "set.default": "Usa Unarchive per gli archivi",
        "language": "Lingua", "language.system": "Sistema", "appearance": "Aspetto",
        "appearance.system": "Sistema", "appearance.light": "Chiaro", "appearance.dark": "Scuro",
        "general": "Generali", "extraction": "Estrazione", "creating": "Crea",
        "reveal.after": "Mostra la destinazione nel Finder dopo l’estrazione",
        "default.format": "Formato predefinito per i nuovi archivi",
        "about.body": "Unarchive è uno strumento nativo per macOS per sfogliare, estrarre e creare archivi. Per Apple Silicon.",
        "version": "Versione %@ (%@)", "copyright": "Copyright © 2026 Shambhala222. Tutti i diritti riservati.",
        "path": "Percorso", "type": "Tipo", "folder": "Cartella", "file": "File", "files": "file",
        "method": "Compressione", "modified": "Modificato", "encrypted": "Crittografato", "yes": "Sì",
        "not.supported": "“%@” non è un archivio supportato.",
        "create.choose": "Scegli file o cartelle da comprimere",
        "create.save": "Salva archivio", "create.failed": "Impossibile creare l’archivio.",
        "create.done": "Archivio creato.", "column.name": "Nome", "column.size": "Dimensione",
        "column.packed": "Compresso", "column.date": "Modificato",
        "reading": "Lettura archivio…", "extracting": "Estrazione…", "preparing": "Preparazione…",
        "testing": "Verifica archivio…", "extracted.to": "Estrazione completata in “%@”.",
        "test.ok": "Verifica riuscita. L’archivio è integro.",
        "test.fail": "La verifica è terminata con errori.\n\n%@",
        "default.ok": "Unarchive ora apre gli archivi con doppio clic.",
        "default.fail": "macOS non ha cambiato l’app predefinita. Ctrl-clic → Apri con → Unarchive → Sempre.",
        "close.archive": "Chiudi", "choose.folder": "Scegli destinazione",
        "pack.note": "Crea ZIP, 7z, TAR, TAR.GZ, TAR.BZ2 o TAR.XZ. La creazione RAR non è inclusa (formato proprietario).",
        "feature.multiselect": "Selezione multipla e trascinamento nel Finder",
        "feature.password": "Richiesta password per archivi protetti",
        "feature.context": "Clic destro per estrarre, aprire o ispezionare",
        "helper.missing": "Motore di estrazione non trovato.",
        "list.failed": "Impossibile leggere l’archivio.", "extract.failed": "Estrazione non riuscita.",
        "not.an.archive": "Questo file non è un archivio supportato.",
        "invalid.listing": "Risposta archivio non valida.", "no.recent": "Nessun archivio recente.",
        "open.selection": "Apri", "credits": "Creato e progettato da Shambhala222",
        "engine": "Motore: UnRAR per RAR · The Unarchiver per ZIP e altri · 7-Zip per creare 7z",
        "legal": "Questo prodotto non è affiliato con WinRAR o RARLAB."
    ]

    private static let pt: [String: String] = [
        "created.by": "Criado por Shambhala222",
        "open": "Abrir", "open.archive": "Abrir arquivo…", "extract.to": "Extrair para…",
        "extract.here": "Extrair no local do arquivo", "extract.folder": "Extrair para pasta", "test": "Testar",
        "search": "Pesquisar", "create": "Criar", "create.archive": "Criar arquivo…",
        "settings": "Ajustes", "about": "Sobre",
        "welcome.title": "Abra qualquer arquivo compactado",
        "welcome.subtitle": "Solte um RAR, ZIP, 7z ou TAR. Arraste arquivos, extraia com um clique ou crie um novo.",
        "drop.title": "Solte o arquivo aqui", "drop.subtitle": "ou escolha um arquivo para ver o conteúdo",
        "formats.unpack": "Extrair", "formats.pack": "Criar", "recent": "Recentes",
        "password": "Senha", "password.enter": "Digite a senha",
        "password.protected": "“%@” está protegido por senha.",
        "password.wrong": "Senha incorreta. Tente novamente.",
        "password.needed.extract": "É necessária uma senha para extrair.",
        "password.needed.open": "É necessária uma senha para abrir.",
        "password.needed.test": "É necessária uma senha para testar.",
        "cancel": "Cancelar", "unpack": "Extrair", "wait": "Aguarde…",
        "notice": "Aviso", "error": "Erro", "ok": "OK",
        "status.idle": "Abra um arquivo ou solte-o nesta janela.",
        "status.selected": "%d selecionados · %d arquivos · %@",
        "status.listing": "%d arquivos · %@ · %@",
        "selection": "Seleção", "show.finder": "Mostrar no Finder", "copy.names": "Copiar nomes",
        "info": "Informações", "set.default": "Usar Unarchive para arquivos",
        "language": "Idioma", "language.system": "Sistema", "appearance": "Aparência",
        "appearance.system": "Sistema", "appearance.light": "Claro", "appearance.dark": "Escuro",
        "general": "Geral", "extraction": "Extração", "creating": "Criar",
        "reveal.after": "Mostrar destino no Finder após extrair",
        "default.format": "Formato padrão para novos arquivos",
        "about.body": "Unarchive é uma ferramenta nativa do macOS para navegar, extrair e criar arquivos. Para Apple Silicon.",
        "version": "Versão %@ (%@)", "copyright": "Copyright © 2026 Shambhala222. Todos os direitos reservados.",
        "path": "Caminho", "type": "Tipo", "folder": "Pasta", "file": "Arquivo", "files": "arquivos",
        "method": "Compressão", "modified": "Modificado", "encrypted": "Criptografado", "yes": "Sim",
        "not.supported": "“%@” não é um arquivo suportado.",
        "create.choose": "Escolha arquivos ou pastas para compactar",
        "create.save": "Salvar arquivo", "create.failed": "Não foi possível criar o arquivo.",
        "create.done": "Arquivo criado.", "column.name": "Nome", "column.size": "Tamanho",
        "column.packed": "Compactado", "column.date": "Modificado",
        "reading": "Lendo arquivo…", "extracting": "Extraindo…", "preparing": "Preparando…",
        "testing": "Testando arquivo…", "extracted.to": "Extração concluída em “%@”.",
        "test.ok": "Teste bem-sucedido. O arquivo está intacto.",
        "test.fail": "O teste terminou com erros.\n\n%@",
        "default.ok": "O Unarchive agora abre arquivos com duplo clique.",
        "default.fail": "O macOS não alterou o app padrão. Clique com o botão direito → Abrir com → Unarchive → Sempre.",
        "close.archive": "Fechar", "choose.folder": "Escolher destino",
        "pack.note": "Crie ZIP, 7z, TAR, TAR.GZ, TAR.BZ2 ou TAR.XZ. Criar RAR não está incluído (formato proprietário).",
        "feature.multiselect": "Seleção múltipla e arrastar para o Finder",
        "feature.password": "Solicita senha em arquivos protegidos",
        "feature.context": "Clique com o botão direito para extrair, ver ou inspecionar",
        "helper.missing": "Mecanismo de extração não encontrado.",
        "list.failed": "Não foi possível ler o arquivo.", "extract.failed": "A extração falhou.",
        "not.an.archive": "Este arquivo não é um arquivo suportado.",
        "invalid.listing": "Resposta de arquivo inválida.", "no.recent": "Nenhum arquivo recente.",
        "open.selection": "Abrir", "credits": "Criado e desenhado por Shambhala222",
        "engine": "Motor: UnRAR para RAR · The Unarchiver para ZIP e outros · 7-Zip para criar 7z",
        "legal": "Este produto não é afiliado à WinRAR ou RARLAB."
    ]

    private static let nl: [String: String] = [
        "created.by": "Gemaakt door Shambhala222",
        "open": "Openen", "open.archive": "Archief openen…", "extract.to": "Uitpakken naar…",
        "extract.here": "Uitpakken bij archief", "extract.folder": "Uitpakken in map", "test": "Testen",
        "search": "Zoeken", "create": "Maken", "create.archive": "Archief maken…",
        "settings": "Instellingen", "about": "Over",
        "welcome.title": "Pak elk archief uit",
        "welcome.subtitle": "Sleep een RAR-, ZIP-, 7z- of TAR-bestand hierheen. Sleep bestanden eruit of maak een nieuw archief.",
        "drop.title": "Zet archief hier neer", "drop.subtitle": "of kies een bestand om de inhoud te zien",
        "formats.unpack": "Uitpakken", "formats.pack": "Maken", "recent": "Recent",
        "password": "Wachtwoord", "password.enter": "Voer wachtwoord in",
        "password.protected": "“%@” is beveiligd met een wachtwoord.",
        "password.wrong": "Onjuist wachtwoord. Probeer opnieuw.",
        "password.needed.extract": "Er is een wachtwoord nodig om uit te pakken.",
        "password.needed.open": "Er is een wachtwoord nodig om te openen.",
        "password.needed.test": "Er is een wachtwoord nodig om te testen.",
        "cancel": "Annuleren", "unpack": "Uitpakken", "wait": "Even geduld…",
        "notice": "Melding", "error": "Fout", "ok": "OK",
        "status.idle": "Open een archief of zet een bestand op dit venster.",
        "status.selected": "%d geselecteerd · %d bestanden · %@",
        "status.listing": "%d bestanden · %@ · %@",
        "selection": "Selectie", "show.finder": "Toon in Finder", "copy.names": "Kopieer namen",
        "info": "Info", "set.default": "Gebruik Unarchive voor archieven",
        "language": "Taal", "language.system": "Systeem", "appearance": "Weergave",
        "appearance.system": "Systeem", "appearance.light": "Licht", "appearance.dark": "Donker",
        "general": "Algemeen", "extraction": "Uitpakken", "creating": "Maken",
        "reveal.after": "Toon bestemming in Finder na uitpakken",
        "default.format": "Standaardformaat voor nieuwe archieven",
        "about.body": "Unarchive is een native macOS-tool om archieven te bekijken, uit te pakken en te maken. Voor Apple Silicon.",
        "version": "Versie %@ (%@)", "copyright": "Copyright © 2026 Shambhala222. Alle rechten voorbehouden.",
        "path": "Pad", "type": "Soort", "folder": "Map", "file": "Bestand", "files": "bestanden",
        "method": "Compressie", "modified": "Gewijzigd", "encrypted": "Versleuteld", "yes": "Ja",
        "not.supported": "“%@” is geen ondersteund archief.",
        "create.choose": "Kies bestanden of mappen om in te pakken",
        "create.save": "Archief bewaren", "create.failed": "Archief kon niet worden gemaakt.",
        "create.done": "Archief gemaakt.", "column.name": "Naam", "column.size": "Grootte",
        "column.packed": "Ingepakt", "column.date": "Gewijzigd",
        "reading": "Archief lezen…", "extracting": "Uitpakken…", "preparing": "Voorbereiden…",
        "testing": "Archief testen…", "extracted.to": "Klaar met uitpakken naar “%@”.",
        "test.ok": "Test geslaagd. Het archief is in orde.",
        "test.fail": "De test is geëindigd met fouten.\n\n%@",
        "default.ok": "Unarchive opent nu archieven met dubbelklikken.",
        "default.fail": "macOS heeft de standaard-app niet gewijzigd. Klik met Control → Openen met → Unarchive → Altijd.",
        "close.archive": "Sluiten", "choose.folder": "Kies bestemming",
        "pack.note": "Maak ZIP, 7z, TAR, TAR.GZ, TAR.BZ2 of TAR.XZ. RAR maken zit er niet in (eigendom van derden).",
        "feature.multiselect": "Meerdere bestanden selecteren en naar Finder slepen",
        "feature.password": "Wachtwoordvraag bij beveiligde archieven",
        "feature.context": "Klik met Control om uit te pakken, te openen of te bekijken",
        "helper.missing": "Uitpak-engine niet gevonden.",
        "list.failed": "Archief kon niet worden gelezen.", "extract.failed": "Uitpakken mislukt.",
        "not.an.archive": "Dit bestand is geen ondersteund archief.",
        "invalid.listing": "Ongeldig archiefantwoord.", "no.recent": "Nog geen recente archieven.",
        "open.selection": "Openen", "credits": "Gemaakt en ontworpen door Shambhala222",
        "engine": "Engine: UnRAR voor RAR · The Unarchiver voor ZIP en andere · 7-Zip voor 7z",
        "legal": "Dit product is niet gelieerd aan WinRAR of RARLAB."
    ]

    private static let pl: [String: String] = [
        "created.by": "Stworzone przez Shambhala222",
        "open": "Otwórz", "open.archive": "Otwórz archiwum…", "extract.to": "Rozpakuj do…",
        "extract.here": "Rozpakuj przy archiwum", "extract.folder": "Rozpakuj do folderu", "test": "Testuj",
        "search": "Szukaj", "create": "Utwórz", "create.archive": "Utwórz archiwum…",
        "settings": "Ustawienia", "about": "O programie",
        "welcome.title": "Otwórz dowolne archiwum",
        "welcome.subtitle": "Upuść plik RAR, ZIP, 7z lub TAR. Przeciągnij pliki, rozpakuj kliknięciem albo utwórz nowe archiwum.",
        "drop.title": "Upuść archiwum tutaj", "drop.subtitle": "albo wybierz plik, by zobaczyć zawartość",
        "formats.unpack": "Rozpakuj", "formats.pack": "Utwórz", "recent": "Ostatnie",
        "password": "Hasło", "password.enter": "Wpisz hasło",
        "password.protected": "„%@” jest chronione hasłem.",
        "password.wrong": "Nieprawidłowe hasło. Spróbuj ponownie.",
        "password.needed.extract": "Do rozpakowania potrzebne jest hasło.",
        "password.needed.open": "Do otwarcia potrzebne jest hasło.",
        "password.needed.test": "Do testu potrzebne jest hasło.",
        "cancel": "Anuluj", "unpack": "Rozpakuj", "wait": "Proszę czekać…",
        "notice": "Informacja", "error": "Błąd", "ok": "OK",
        "status.idle": "Otwórz archiwum lub upuść plik na to okno.",
        "status.selected": "%d zaznaczonych · %d plików · %@",
        "status.listing": "%d plików · %@ · %@",
        "selection": "Zaznaczenie", "show.finder": "Pokaż w Finderze", "copy.names": "Kopiuj nazwy",
        "info": "Informacje", "set.default": "Używaj Unarchive do archiwów",
        "language": "Język", "language.system": "System", "appearance": "Wygląd",
        "appearance.system": "System", "appearance.light": "Jasny", "appearance.dark": "Ciemny",
        "general": "Ogólne", "extraction": "Rozpakowywanie", "creating": "Tworzenie",
        "reveal.after": "Pokaż folder docelowy w Finderze po rozpakowaniu",
        "default.format": "Domyślny format nowych archiwów",
        "about.body": "Unarchive to natywne narzędzie macOS do przeglądania, rozpakowywania i tworzenia archiwów. Dla Apple Silicon.",
        "version": "Wersja %@ (%@)", "copyright": "Copyright © 2026 Shambhala222. Wszelkie prawa zastrzeżone.",
        "path": "Ścieżka", "type": "Rodzaj", "folder": "Folder", "file": "Plik", "files": "plików",
        "method": "Kompresja", "modified": "Zmieniono", "encrypted": "Szyfrowane", "yes": "Tak",
        "not.supported": "„%@” nie jest obsługiwanym archiwum.",
        "create.choose": "Wybierz pliki lub foldery do spakowania",
        "create.save": "Zapisz archiwum", "create.failed": "Nie udało się utworzyć archiwum.",
        "create.done": "Archiwum utworzone.", "column.name": "Nazwa", "column.size": "Rozmiar",
        "column.packed": "Spakowane", "column.date": "Zmieniono",
        "reading": "Odczyt archiwum…", "extracting": "Rozpakowywanie…", "preparing": "Przygotowywanie…",
        "testing": "Testowanie archiwum…", "extracted.to": "Rozpakowano do „%@”.",
        "test.ok": "Test zakończony pomyślnie. Archiwum jest w porządku.",
        "test.fail": "Test zakończył się błędami.\n\n%@",
        "default.ok": "Unarchive otwiera teraz archiwa po dwukrotnym kliknięciu.",
        "default.fail": "macOS nie zmienił domyślnej aplikacji. Kliknij z Control → Otwórz w programie → Unarchive → Zawsze.",
        "close.archive": "Zamknij", "choose.folder": "Wybierz miejsce docelowe",
        "pack.note": "Twórz ZIP, 7z, TAR, TAR.GZ, TAR.BZ2 lub TAR.XZ. Tworzenie RAR nie jest dostępne (format zastrzeżony).",
        "feature.multiselect": "Zaznaczanie wielu plików i przeciąganie do Findera",
        "feature.password": "Pytanie o hasło przy chronionych archiwach",
        "feature.context": "Kliknięcie z Control, by rozpakować, otworzyć lub sprawdzić",
        "helper.missing": "Nie znaleziono silnika rozpakowującego.",
        "list.failed": "Nie można odczytać archiwum.", "extract.failed": "Rozpakowywanie nie powiodło się.",
        "not.an.archive": "Ten plik nie jest obsługiwanym archiwum.",
        "invalid.listing": "Nieprawidłowa odpowiedź archiwum.", "no.recent": "Brak ostatnich archiwów.",
        "open.selection": "Otwórz", "credits": "Stworzone i zaprojektowane przez Shambhala222",
        "engine": "Silnik: UnRAR dla RAR · The Unarchiver dla ZIP i innych · 7-Zip do tworzenia 7z",
        "legal": "Ten produkt nie jest powiązany z WinRAR ani RARLAB."
    ]

    private static let ja: [String: String] = [
        "created.by": "作成者: Shambhala222",
        "open": "開く", "open.archive": "アーカイブを開く…", "extract.to": "展開先…",
        "extract.here": "アーカイブの場所に展開", "extract.folder": "フォルダに展開", "test": "テスト",
        "search": "検索", "create": "作成", "create.archive": "アーカイブを作成…",
        "settings": "設定", "about": "このアプリについて",
        "welcome.title": "どんなアーカイブも展開",
        "welcome.subtitle": "RAR、ZIP、7z、TAR をここにドロップ。ファイルをドラッグして取り出すか、新しいアーカイブを作成できます。",
        "drop.title": "アーカイブをここにドロップ", "drop.subtitle": "またはファイルを選んで中身を表示",
        "formats.unpack": "展開", "formats.pack": "作成", "recent": "最近",
        "password": "パスワード", "password.enter": "パスワードを入力",
        "password.protected": "“%@” はパスワードで保護されています。",
        "password.wrong": "パスワードが違います。もう一度入力してください。",
        "password.needed.extract": "展開するにはパスワードが必要です。",
        "password.needed.open": "開くにはパスワードが必要です。",
        "password.needed.test": "テストするにはパスワードが必要です。",
        "cancel": "キャンセル", "unpack": "展開", "wait": "お待ちください…",
        "notice": "お知らせ", "error": "エラー", "ok": "OK",
        "status.idle": "アーカイブを開くか、このウィンドウにドロップしてください。",
        "status.selected": "%d 件選択 · %d ファイル · %@",
        "status.listing": "%d ファイル · %@ · %@",
        "selection": "選択", "show.finder": "Finder に表示", "copy.names": "名前をコピー",
        "info": "情報", "set.default": "アーカイブを Unarchive で開く",
        "language": "言語", "language.system": "システム", "appearance": "外観",
        "appearance.system": "システム", "appearance.light": "ライト", "appearance.dark": "ダーク",
        "general": "一般", "extraction": "展開", "creating": "作成",
        "reveal.after": "展開後に Finder で保存先を表示",
        "default.format": "新規アーカイブのデフォルト形式",
        "about.body": "Unarchive はアーカイブの閲覧・展開・作成のためのネイティブ macOS アプリです。Apple Silicon 向け。",
        "version": "バージョン %@ (%@)", "copyright": "Copyright © 2026 Shambhala222. All rights reserved.",
        "path": "パス", "type": "種類", "folder": "フォルダ", "file": "ファイル", "files": "ファイル",
        "method": "圧縮", "modified": "変更日", "encrypted": "暗号化", "yes": "はい",
        "not.supported": "“%@” は対応していないアーカイブです。",
        "create.choose": "パックするファイルまたはフォルダを選択",
        "create.save": "アーカイブを保存", "create.failed": "アーカイブを作成できませんでした。",
        "create.done": "アーカイブを作成しました。", "column.name": "名前", "column.size": "サイズ",
        "column.packed": "圧縮後", "column.date": "変更日",
        "reading": "アーカイブを読み込み中…", "extracting": "展開中…", "preparing": "準備中…",
        "testing": "アーカイブをテスト中…", "extracted.to": "“%@” への展開が完了しました。",
        "test.ok": "テストに成功しました。アーカイブは正常です。",
        "test.fail": "テストでエラーがありました。\n\n%@",
        "default.ok": "ダブルクリックで Unarchive がアーカイブを開きます。",
        "default.fail": "macOS がデフォルトを変更しませんでした。右クリック → このアプリケーションで開く → Unarchive → 常に。",
        "close.archive": "閉じる", "choose.folder": "保存先を選択",
        "pack.note": "ZIP、7z、TAR、TAR.GZ、TAR.BZ2、TAR.XZ を作成できます。RAR の作成は含まれません（独自形式）。",
        "feature.multiselect": "複数選択して Finder にドラッグ",
        "feature.password": "保護されたアーカイブではパスワードを要求",
        "feature.context": "右クリックで展開、表示、情報",
        "helper.missing": "展開エンジンが見つかりません。",
        "list.failed": "アーカイブを読み込めませんでした。", "extract.failed": "展開に失敗しました。",
        "not.an.archive": "このファイルは対応していないアーカイブです。",
        "invalid.listing": "無効なアーカイブ応答です。", "no.recent": "最近のアーカイブはありません。",
        "open.selection": "開く", "credits": "作成・デザイン: Shambhala222",
        "engine": "エンジン: RAR は UnRAR · ZIP などは The Unarchiver · 7z 作成は 7-Zip",
        "legal": "WinRAR および RARLAB とは関係ありません。"
    ]

    private static let zh: [String: String] = [
        "created.by": "由 Shambhala222 创建",
        "open": "打开", "open.archive": "打开压缩包…", "extract.to": "解压到…",
        "extract.here": "解压到压缩包所在位置", "extract.folder": "解压到文件夹", "test": "测试",
        "search": "搜索", "create": "创建", "create.archive": "创建压缩包…",
        "settings": "设置", "about": "关于",
        "welcome.title": "打开任意压缩包",
        "welcome.subtitle": "将 RAR、ZIP、7z 或 TAR 拖到这里。可拖出文件、一键解压，或创建新压缩包。",
        "drop.title": "将压缩包拖到这里", "drop.subtitle": "或选择文件以查看内容",
        "formats.unpack": "解压", "formats.pack": "创建", "recent": "最近",
        "password": "密码", "password.enter": "输入密码",
        "password.protected": "“%@” 已加密。",
        "password.wrong": "密码不正确，请重试。",
        "password.needed.extract": "解压需要密码。",
        "password.needed.open": "打开需要密码。",
        "password.needed.test": "测试需要密码。",
        "cancel": "取消", "unpack": "解压", "wait": "请稍候…",
        "notice": "提示", "error": "错误", "ok": "好",
        "status.idle": "打开压缩包，或将其拖到此窗口。",
        "status.selected": "已选 %d 项 · %d 个文件 · %@",
        "status.listing": "%d 个文件 · %@ · %@",
        "selection": "选择", "show.finder": "在 Finder 中显示", "copy.names": "拷贝名称",
        "info": "显示简介", "set.default": "用 Unarchive 打开压缩包",
        "language": "语言", "language.system": "系统", "appearance": "外观",
        "appearance.system": "系统", "appearance.light": "浅色", "appearance.dark": "深色",
        "general": "通用", "extraction": "解压", "creating": "创建",
        "reveal.after": "解压后在 Finder 中显示目标位置",
        "default.format": "新建压缩包的默认格式",
        "about.body": "Unarchive 是用于浏览、解压和创建压缩包的原生 macOS 工具，专为 Apple 芯片打造。",
        "version": "版本 %@ (%@)", "copyright": "Copyright © 2026 Shambhala222. 保留所有权利。",
        "path": "路径", "type": "种类", "folder": "文件夹", "file": "文件", "files": "个文件",
        "method": "压缩方式", "modified": "修改时间", "encrypted": "已加密", "yes": "是",
        "not.supported": "“%@” 不是支持的压缩包。",
        "create.choose": "选择要打包的文件或文件夹",
        "create.save": "存储压缩包", "create.failed": "无法创建压缩包。",
        "create.done": "已创建压缩包。", "column.name": "名称", "column.size": "大小",
        "column.packed": "压缩后", "column.date": "修改时间",
        "reading": "正在读取压缩包…", "extracting": "正在解压…", "preparing": "正在准备…",
        "testing": "正在测试压缩包…", "extracted.to": "已解压到“%@”。",
        "test.ok": "测试成功，压缩包完好。",
        "test.fail": "测试完成，但存在错误。\n\n%@",
        "default.ok": "现在双击即可用 Unarchive 打开压缩包。",
        "default.fail": "macOS 未更改默认应用。按住 Control 点按 → 打开方式 → Unarchive → 始终。",
        "close.archive": "关闭", "choose.folder": "选择目标位置",
        "pack.note": "可创建 ZIP、7z、TAR、TAR.GZ、TAR.BZ2 或 TAR.XZ。不包含创建 RAR（专有格式）。",
        "feature.multiselect": "多选文件并拖到 Finder",
        "feature.password": "加密压缩包会提示输入密码",
        "feature.context": "按住 Control 点按即可解压、打开或查看信息",
        "helper.missing": "找不到解压引擎。",
        "list.failed": "无法读取压缩包。", "extract.failed": "解压失败。",
        "not.an.archive": "此文件不是支持的压缩包。",
        "invalid.listing": "压缩包响应无效。", "no.recent": "暂无最近打开的压缩包。",
        "open.selection": "打开", "credits": "由 Shambhala222 创建和设计",
        "engine": "引擎：RAR 使用 UnRAR · ZIP 等使用 The Unarchiver · 使用 7-Zip 创建 7z",
        "legal": "本产品与 WinRAR 或 RARLAB 无关。"
    ]
}
